version: "3.8"
services:
  backend:
    build: . # Build image from local Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: test
    ports:
      - "3001:3001" # Expose port 3000 on host
    depends_on:
      - db # Wait until database service is loaded
    networks:
      - app-network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    networks:
      - app-network
networks: # Specify the network for bridging
  app-network:
    driver: bridge